### ISSUE TITLE
Please add https://topsecretrecipes.com to list of supported sites

### ISSUE THREAD

**Issue by RockyJE** [judemont/reciper#2]
Firstly, Thank You! for the app.

I imagine that once the word gets around about this app you'll be getting lots of requests for sites, so here's mine:

Please add https://topsecretrecipes.com

Lots of copy-cat recipes from restaurants, and such.

...
Could you add option(s) for Export to file types other than .json? Plaintext, mainly, but Markdown would be great, too.

Also, I was hoping this app could do is extract info from locally stored files that are in html format. I only have a few, and it's not that important to me, but was just wondering if it could be implemented in future releases.

Thanks again

**Comment by judemont** [comment]
Hi @RockyJE,
I've added support for topsecretrecipes.com in the new release: https://github.com/judemont/reciper/releases/tag/v2.1.0

About the options to export in text/markdown format (and also in pdf I think), it's a good idea and I think I'll implement it when I have time (Maybe this week...).

**Comment by RockyJE** [comment]
Thank you! I was gonna mention PDF, but didn't want to sound too, umm, demanding, or whatever.
