### ISSUE TITLE
Cannot extracting these recipes

### ISSUE THREAD

**Issue by serrq** [judemont/reciper#8]
• https://ricette.giallozafferano.it/Insalata-di-riso-integrale.html

• https://ricette.giallozafferano.it/Petto-di-pollo-peperoni-e-olive.html

• https://www.cucchiaio.it/ricetta/pancake-con-3-ingredienti/

Untare app (unofficial tandoor android client) can extracting them.

**Comment by judemont** [comment]
Hi @serrq ,
I've added support for "giallozafferano" and "cucchiaio" in the new release 🫡 !

https://github.com/judemont/reciper/releases/latest
